led.plot(4, 4)
led.plot(4, 3)
led.plot(4, 2)
led.plot(4, 1)
led.plot(4, 0)
led.plot(3, 4)
led.plot(3, 3)
led.plot(2, 3)
led.plot(1, 3)
led.plot(1, 4)
led.plot(0, 3)
led.plot(4, 2)
led.plot(3, 2)
led.plot(2, 4)
led.plot(2, 2)
led.plot(1, 2)
led.plot(0, 2)
led.plot(4, 1)
led.plot(3, 1)
led.plot(2, 1)
led.plot(1, 1)
led.plot(0, 1)
led.plot(4, 0)
led.plot(3, 0)
led.plot(2, 0)
led.plot(0, 4)
led.plot(1, 0)
led.plot(0, 0)

def on_button_pressed_a():
    music.start_melody(music.built_in_melody(Melodies.DADADADUM),
        MelodyOptions.ONCE)
input.on_button_pressed(Button.A, on_button_pressed_a)
